// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Availability(arg1, arg2) {
  return window['go']['main']['App']['Availability'](arg1, arg2);
}

export function Claim(arg1) {
  return window['go']['main']['App']['Claim'](arg1);
}

export function CreateZone(arg1, arg2) {
  return window['go']['main']['App']['CreateZone'](arg1, arg2);
}

export function DaemonDown() {
  return window['go']['main']['App']['DaemonDown']();
}

export function DaemonUp() {
  return window['go']['main']['App']['DaemonUp']();
}

export function GetMap() {
  return window['go']['main']['App']['GetMap']();
}

export function GetPorts() {
  return window['go']['main']['App']['GetPorts']();
}

export function GetProcesses() {
  return window['go']['main']['App']['GetProcesses']();
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetTree() {
  return window['go']['main']['App']['GetTree']();
}

export function KillPort(arg1, arg2) {
  return window['go']['main']['App']['KillPort'](arg1, arg2);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function ProcessLogs(arg1, arg2) {
  return window['go']['main']['App']['ProcessLogs'](arg1, arg2);
}

export function Release(arg1) {
  return window['go']['main']['App']['Release'](arg1);
}

export function Rename(arg1, arg2) {
  return window['go']['main']['App']['Rename'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StartProcess(arg1) {
  return window['go']['main']['App']['StartProcess'](arg1);
}

export function StopProcess(arg1) {
  return window['go']['main']['App']['StopProcess'](arg1);
}
