// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Availability(arg1:string,arg2:string):Promise<Record<string, any>>;

export function Claim(arg1:main.ClaimInput):Promise<void>;

export function DaemonDown():Promise<string>;

export function DaemonUp():Promise<string>;

export function GetPorts():Promise<main.PortsView>;

export function GetProcesses():Promise<Array<Record<string, any>>>;

export function GetSettings():Promise<main.Settings>;

export function GetStatus():Promise<main.Status>;

export function GetTree():Promise<Array<main.TreeNode>>;

export function KillPort(arg1:number,arg2:boolean):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function ProcessLogs(arg1:string,arg2:number):Promise<Array<string>>;

export function Release(arg1:number):Promise<void>;

export function Rename(arg1:number,arg2:string):Promise<void>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function StartProcess(arg1:string):Promise<void>;

export function StopProcess(arg1:string):Promise<void>;
